# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b2d856f1619e70c620c5f07f478908171774daf941848970b46f666aebafbfe00b16b784da9d9da6d5727e28e63b60515604f7c3d119b2cc6a4d6e9c2a14e50

test:
  secret_key_base: ec13dc908cdb0fb07f1e9545f07cc30b5414e3b598d930148c60d322fa60cdafead453821f618f051947a8e357317082e5bc5dd570f2719eee17412e77eabd38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
